CREATE TABLE app (
  appId INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(70) DEFAULT NULL,
  code VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (appId)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;


CREATE TABLE user (
  userId INT(11) NOT NULL AUTO_INCREMENT,
  login VARCHAR(50) DEFAULT NULL,
  fullname VARCHAR(50) DEFAULT NULL,
  `password` VARCHAR(64) DEFAULT NULL,
  role ENUM('user','admin') NOT NULL DEFAULT 'user',
  PRIMARY KEY (userId),
  UNIQUE INDEX login (login)
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE userAppRule (
  userId INT(11) NOT NULL,
  appId INT(11) NOT NULL,
  rule ENUM('ALLOW','DENY') NOT NULL DEFAULT 'ALLOW',
  CONSTRAINT FK_userAppRule_app_appId FOREIGN KEY (appId)
    REFERENCES app(appId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_userAppRule_user_userId FOREIGN KEY (userId)
    REFERENCES user(userId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE worker (
  uuid VARCHAR(48) NOT NULL,
  startDate DATETIME NOT NULL,
  endDate DATETIME DEFAULT NULL,
  appId INT(11) NOT NULL,
  userId INT(11) NOT NULL,
  status ENUM('ALIVE','DIED','SUCCESS','ERROR') NOT NULL DEFAULT 'ALIVE',
  PRIMARY KEY (uuid),
  CONSTRAINT FK_worker_app_appId FOREIGN KEY (appId)
    REFERENCES app(appId) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT FK_worker_user_userId FOREIGN KEY (userId)
    REFERENCES user(userId) ON DELETE RESTRICT ON UPDATE RESTRICT
)
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;